# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicAppClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicAppClone
  pod 'RxSwift', '6.7.1'
  pod 'RxCocoa', '6.7.1'
  pod 'FlexLayout'
  pod 'PinLayout'

  target 'MusicAppCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicAppCloneUITests' do
    # Pods for testing
  end

end
